/*
 * Copyright (c) 2026 Contributors to the Eclipse Foundation.
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Data In Motion Consulting - initial implementation
 */
package org.eclipse.fennec.odata.vocabularies;

import java.util.ArrayList;
import java.util.Hashtable;
import java.util.List;

import org.eclipse.emf.ecore.EPackage;
import org.osgi.framework.BundleContext;
import org.osgi.framework.ServiceRegistration;
import org.osgi.service.component.annotations.Activate;
import org.osgi.service.component.annotations.Component;
import org.osgi.service.component.annotations.Deactivate;

/**
 * Registers the OASIS vocabulary {@link EPackage}s as OSGi services on activation, so the
 * Model Metadata Service whiteboard (and any other EPackage consumer) picks them up — the
 * same contract as model bundles generated by the EMF-OSGi codegen.
 */
@Component(immediate = true)
public class ODataVocabulariesComponent {

	private final List<ServiceRegistration<EPackage>> registrations = new ArrayList<>();

	@Activate
	void activate(BundleContext context) {
		for (String namespace : ODataVocabularies.all()) {
			EPackage pkg = ODataVocabularies.getEPackage(namespace);
			Hashtable<String, Object> props = new Hashtable<>();
			props.put("emf.nsURI", pkg.getNsURI());
			props.put("emf.name", pkg.getName());
			registrations.add(context.registerService(EPackage.class, pkg, props));
		}
	}

	@Deactivate
	void deactivate() {
		registrations.forEach(ServiceRegistration::unregister);
		registrations.clear();
	}
}
